steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh Student@german-bot --zone=us-central1-a --project=learn-german-bot --command="cd /home/Student/germanflashcards && git pull --ff-only && sudo systemctl restart germanbot"
options:
  logging: CLOUD_LOGGING_ONLY